language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t riteshvaryani/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true riteshvaryani/docker-react npm run test